### ISSUE TITLE
check_names fails if all species names are correct

### ISSUE THREAD

**Issue by Lobz** [wevertonbio/florabr#17]
Reproducing this simple variation on the function example:
```r
data("bf_data", package = "florabr")
spp <- c("Butia catarinensis", "Araucaria angustifolia")
check_names(data = bf_data, species = spp)
```
Results in the following error:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': object 'sp_l' not found
```
I haven't tested all the other functions, it's possible they have the same issue

**Comment by wevertonbio** [comment]
Hi,
Thank you so much for your feedback!
I’ve fixed the function, and it now correctly returns results even when all species names are spelled correctly. Please install the development version from GitHub

`remotes::install_github("wevertonbio/florabr")`

I’ll submit the modifications to CRAN as soon as possible.
